import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
//https://github.com/FredericRezeau/idle-bignum/blob/master/idle-bignum.js
class BigNumber extends StatefulWidget {
  final int value;
  final int exponent;
  const BigNumber({ Key? key, required this.value, required this.exponent }): super(key: key);

  @override
  State<BigNumber> createState() => _BigNumberState();
}

class _BigNumberState extends State<BigNumber> {
  Map<int, String> powTenToName = {
    0: "",
    3: "thousand",
    6: "million",
    9: "billion",
    12: "trillion",
    15: "quadrillion",
    18: "quintillion",
    21: "sextillion",
    24: "septillion",
    27: "octillion",
    30: "nonillion",
    33: "decillion",
    36: "undecillion",
    39: "duodecillion",
    42: "tredecillion",
    45: "quattuordecillion",
    48: "quindecillion",
    51: "sedecillion",
    54: "septendecillion",
    57: "octodecillion",
    60: "novendecillion",
    63: "vigintillion",
    66: "unvigintillion",
    69: "duovigintillion",
    72: "tresvigintillion",
    75: "quattuorvigintillion",
    78: "quinvigintillion",
    81: "sesvigintillion",
    84: "septemvigintillion",
    87: "octovigintillion",
    90: "novemvigintillion",
    93: "trigintillion",
    96: "untrigintillion",
    99: "duotrigintillion",
    102: "trestrigintillion",
    105: "quattuortrigintillion",
    108: "quintrigintillion",
    111: "sestrigintillion",
    114: "septentrigintillion",
    117: "octotrigintillion",
    120: "noventrigintillion",
    123: "quadragintillion",
    126: "unquadragintillion",
    129: "duoquadragintillion",
    132: "tresquadragintillion",
    135: "quattuorquadragintillion",
    138: "quinquadragintillion",
    141: "sesquadragintillion",
    144: "septenquadragintillion",
    147: "octoquadragintillion",
    150: "novenquadragintillion",
    153: "quinquagintillion",
    156: "unquinquagintillion",
    159: "duoquinquagintillion",
    162: "tresquinquagintillion",
    165: "quattuorquinquagintillion",
    168: "quinquinquagintillion",
    171: "sesquinquagintillion",
    174: "septenquinquagintillion",
    177: "octoquinquagintillion",
    180: "novenquinquagintillion",
    183: "sexagintillion",
    186: "unsexagintillion",
    189: "duosexagintillion",
    192: "tresexagintillion",
    195: "quattuorsexagintillion",
    198: "quinsexagintillion",
    201: "sesexagintillion",
    204: "septensexagintillion",
    207: "octosexagintillion",
    210: "novensexagintillion",
    213: "septuagintillion",
    216: "unseptuagintillion",
    219: "duoseptuagintillion",
    222: "treseptuagintillion",
    225: "quattuorseptuagintillion",
    228: "quinseptuagintillion",
    231: "seseptuagintillion",
    234: "septenseptuagintillion",
    237: "octoseptuagintillion",
    240: "novenseptuagintillion",
    243: "octogintillion",
    246: "unoctogintillion",
    249: "duooctogintillion",
    252: "tresoctogintillion",
    255: "quattuoroctogintillion",
    258: "quinoctogintillion",
    261: "sexoctogintillion",
    264: "septemoctogintillion",
    267: "octooctogintillion",
    270: "novemoctogintillion",
    273: "nonagintillion",
    276: "unnonagintillion",
    279: "duononagintillion",
    282: "trenonagintillion",
    285: "quattuornonagintillion",
    288: "quinnonagintillion",
    291: "senonagintillion",
    294: "septenonagintillion",
    297: "octononagintillion",
    300: "novenonagintillion",
    303: "centillion",
    306: "uncentillion",
    309: "duocentillion",
    312: "trescentillion",
    315: "quattuorcentillion",
    318: "quincentillion",
    321: "sexcentillion",
    324: "septencentillion",
    327: "octocentillion",
    330: "novencentillion",
    333: "decicentillion"
  };
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
